# Generated by Django 3.2 on 2021-07-09 13:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('unique_id', models.CharField(default=uuid.uuid4, editable=False, max_length=120, unique=True)),
                ('capex_fix', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('capex_var', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('opex_fix', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('opex_var', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('lifetime', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('input_timeseries', models.TextField(null=True)),
                ('crate', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('efficiency', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('soc_max', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('soc_min', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('dispatchable', models.BooleanField(choices=[(None, 'Choose'), (True, 'Yes'), (False, 'No')], default=None, null=True)),
                ('maximum_capacity', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('energy_price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('feedin_tariff', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('peak_demand_pricing', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('peak_demand_pricing_period', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('renewable_share', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('renewable_asset', models.BooleanField(choices=[(None, 'Choose'), (True, 'Yes'), (False, 'No')], default=None, null=True)),
                ('optimize_cap', models.BooleanField(choices=[(None, 'Choose'), (True, 'Yes'), (False, 'No')], null=True)),
                ('installed_capacity', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('age_installed', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('', 'Choose...'), ('dso', 'dso'), ('gas_dso', 'gas_dso'), ('h2_dso', 'h2_dso'), ('heat_dso', 'heat_dso'), ('demand', 'demand'), ('gas_demand', 'gas_demand'), ('h2_demand', 'h2_demand'), ('heat_demand', 'heat_demand'), ('transformer_station_in', 'transformer_station_in'), ('transformer_station_out', 'transformer_station_out'), ('storage_charge_controller_in', 'storage_charge_controller_in'), ('storage_charge_controller_out', 'storage_charge_controller_out'), ('solar_inverter', 'solar_inverter'), ('diesel_generator', 'diesel_generator'), ('fuel_cell', 'fuel_cell'), ('gas_boiler', 'gas_boiler'), ('electrolyzer', 'electrolyzer'), ('heat_pump', 'heat_pump'), ('pv_plant', 'pv_plant'), ('wind_plant', 'wind_plant'), ('biogas_plant', 'biogas_plant'), ('geothermal_conversion', 'geothermal_conversion'), ('solar_thermal_plant', 'solar_thermal_plant'), ('charging_power', 'charging_power'), ('discharging_power', 'discharging_power'), ('capacity', 'capacity'), ('bess', 'bess'), ('gess', 'gess'), ('h2ess', 'h2ess'), ('hess', 'hess')], max_length=30, unique=True)),
                ('asset_category', models.CharField(choices=[('', 'Choose...'), ('energy_provider', 'energy_provider'), ('energy_production', 'energy_production'), ('energy_conversion', 'energy_conversion'), ('energy_storage', 'energy_storage'), ('energy_consumption', 'energy_consumption')], max_length=30)),
                ('energy_vector', models.CharField(choices=[('', 'Choose...'), ('Electricity', 'Electricity'), ('Heat', 'Heat'), ('Gas', 'Gas'), ('H2', 'H2')], max_length=20)),
                ('mvs_type', models.CharField(choices=[('', 'Choose...'), ('source', 'source'), ('sink', 'sink'), ('transformer', 'transformer'), ('storage', 'storage')], max_length=20)),
                ('asset_fields', models.TextField(null=True)),
                ('unit', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('type', models.CharField(choices=[('', 'Choose...'), ('Electricity', 'Electricity'), ('Heat', 'Heat'), ('Gas', 'Gas'), ('H2', 'H2')], max_length=20)),
                ('input_ports', models.IntegerField(default=1)),
                ('output_ports', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_connection_port', models.CharField(max_length=12)),
                ('flow_direction', models.CharField(choices=[('B2A', 'Bus_to_Asset'), ('A2B', 'Asset_to_Bus')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EconomicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField()),
                ('currency', models.CharField(choices=[('', 'Choose...'), ('EUR', 'EUR'), ('NOK', 'NOK'), ('USD', 'USD'), ('GBP', 'GBP')], max_length=3)),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('tax', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('feedback', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('country', models.CharField(choices=[('', 'Choose...'), ('AFGHANISTAN', 'AFGHANISTAN'), ('ALBANIA', 'ALBANIA'), ('ALGERIA', 'ALGERIA'), ('AMERICAN SAMOA', 'AMERICAN SAMOA'), ('ANDORRA', 'ANDORRA'), ('ANGOLA', 'ANGOLA'), ('ANGUILLA', 'ANGUILLA'), ('ANTARCTICA', 'ANTARCTICA'), ('ANTIGUA AND BARBUDA', 'ANTIGUA AND BARBUDA'), ('ARGENTINA', 'ARGENTINA'), ('ARMENIA', 'ARMENIA'), ('ARUBA', 'ARUBA'), ('AUSTRALIA', 'AUSTRALIA'), ('AUSTRIA', 'AUSTRIA'), ('AZERBAIJAN', 'AZERBAIJAN'), ('BAHAMAS', 'BAHAMAS'), ('BAHRAIN', 'BAHRAIN'), ('BANGLADESH', 'BANGLADESH'), ('BARBADOS', 'BARBADOS'), ('BELARUS', 'BELARUS'), ('BELGIUM', 'BELGIUM'), ('BELIZE', 'BELIZE'), ('BENIN', 'BENIN'), ('BERMUDA', 'BERMUDA'), ('BHUTAN', 'BHUTAN'), ('BOLIVIA', 'BOLIVIA'), ('BOSNIA AND HERZEGOVINA', 'BOSNIA AND HERZEGOVINA'), ('BOTSWANA', 'BOTSWANA'), ('BOUVET ISLAND', 'BOUVET ISLAND'), ('BRAZIL', 'BRAZIL'), ('BRITISH INDIAN OCEAN TERRITORY', 'BRITISH INDIAN OCEAN TERRITORY'), ('BRUNEI DARUSSALAM', 'BRUNEI DARUSSALAM'), ('BULGARIA', 'BULGARIA'), ('BURKINA FASO', 'BURKINA FASO'), ('BURUNDI', 'BURUNDI'), ('CAMBODIA', 'CAMBODIA'), ('CAMEROON', 'CAMEROON'), ('CANADA', 'CANADA'), ('CAPE VERDE', 'CAPE VERDE'), ('CAYMAN ISLANDS', 'CAYMAN ISLANDS'), ('CENTRAL AFRICAN REPUBLIC', 'CENTRAL AFRICAN REPUBLIC'), ('CHAD', 'CHAD'), ('CHILE', 'CHILE'), ('CHINA', 'CHINA'), ('CHRISTMAS ISLAND', 'CHRISTMAS ISLAND'), ('COCOS (KEELING) ISLANDS', 'COCOS (KEELING) ISLANDS'), ('COLOMBIA', 'COLOMBIA'), ('COMOROS', 'COMOROS'), ('CONGO', 'CONGO'), ('CONGO, THE DEMOCRATIC REPUBLIC OF', 'CONGO, THE DEMOCRATIC REPUBLIC OF'), ('COOK ISLANDS', 'COOK ISLANDS'), ('COSTA RICA', 'COSTA RICA'), ("CÃ”TE D'IVOIRE", "CÃ”TE D'IVOIRE"), ('CROATIA', 'CROATIA'), ('CUBA', 'CUBA'), ('CYPRUS', 'CYPRUS'), ('CZECH REPUBLIC', 'CZECH REPUBLIC'), ('DENMARK', 'DENMARK'), ('DJIBOUTI', 'DJIBOUTI'), ('DOMINICA', 'DOMINICA'), ('DOMINICAN REPUBLIC', 'DOMINICAN REPUBLIC'), ('ECUADOR', 'ECUADOR'), ('EGYPT', 'EGYPT'), ('EL SALVADOR', 'EL SALVADOR'), ('EQUATORIAL GUINEA', 'EQUATORIAL GUINEA'), ('ERITREA', 'ERITREA'), ('ESTONIA', 'ESTONIA'), ('ETHIOPIA', 'ETHIOPIA'), ('FALKLAND ISLANDS (MALVINAS)', 'FALKLAND ISLANDS (MALVINAS)'), ('FAROE ISLANDS', 'FAROE ISLANDS'), ('FIJI', 'FIJI'), ('FINLAND', 'FINLAND'), ('FRANCE', 'FRANCE'), ('FRENCH GUIANA', 'FRENCH GUIANA'), ('FRENCH POLYNESIA', 'FRENCH POLYNESIA'), ('FRENCH SOUTHERN TERRITORIES', 'FRENCH SOUTHERN TERRITORIES'), ('GABON', 'GABON'), ('GAMBIA', 'GAMBIA'), ('GEORGIA', 'GEORGIA'), ('GERMANY', 'GERMANY'), ('GHANA', 'GHANA'), ('GIBRALTAR', 'GIBRALTAR'), ('GREECE', 'GREECE'), ('GREENLAND', 'GREENLAND'), ('GRENADA', 'GRENADA'), ('GUADELOUPE', 'GUADELOUPE'), ('GUAM', 'GUAM'), ('GUATEMALA', 'GUATEMALA'), ('GUINEA', 'GUINEA'), ('GUINEA', 'GUINEA'), ('GUYANA', 'GUYANA'), ('HAITI', 'HAITI'), ('HEARD ISLAND AND MCDONALD ISLANDS', 'HEARD ISLAND AND MCDONALD ISLANDS'), ('HONDURAS', 'HONDURAS'), ('HONG KONG', 'HONG KONG'), ('HUNGARY', 'HUNGARY'), ('ICELAND', 'ICELAND'), ('INDIA', 'INDIA'), ('INDONESIA', 'INDONESIA'), ('IRAN, ISLAMIC REPUBLIC OF', 'IRAN, ISLAMIC REPUBLIC OF'), ('IRAQ', 'IRAQ'), ('IRELAND', 'IRELAND'), ('ISRAEL', 'ISRAEL'), ('ITALY', 'ITALY'), ('JAMAICA', 'JAMAICA'), ('JAPAN', 'JAPAN'), ('JORDAN', 'JORDAN'), ('KAZAKHSTAN', 'KAZAKHSTAN'), ('KENYA', 'KENYA'), ('KIRIBATI', 'KIRIBATI'), ("KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"), ('KOREA, REPUBLIC OF', 'KOREA, REPUBLIC OF'), ('KUWAIT', 'KUWAIT'), ('KYRGYZSTAN', 'KYRGYZSTAN'), ("LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LAO PEOPLE'S DEMOCRATIC REPUBLIC"), ('LATVIA', 'LATVIA'), ('LEBANON', 'LEBANON'), ('LESOTHO', 'LESOTHO'), ('LIBERIA', 'LIBERIA'), ('LIBYAN ARAB JAMAHIRIYA', 'LIBYAN ARAB JAMAHIRIYA'), ('LIECHTENSTEIN', 'LIECHTENSTEIN'), ('LITHUANIA', 'LITHUANIA'), ('LUXEMBOURG', 'LUXEMBOURG'), ('MACAO', 'MACAO'), ('MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF'), ('MADAGASCAR', 'MADAGASCAR'), ('MALAWI', 'MALAWI'), ('MALAYSIA', 'MALAYSIA'), ('MALDIVES', 'MALDIVES'), ('MALI', 'MALI'), ('MALTA', 'MALTA'), ('MARSHALL ISLANDS', 'MARSHALL ISLANDS'), ('MARTINIQUE', 'MARTINIQUE'), ('MAURITANIA', 'MAURITANIA'), ('MAURITIUS', 'MAURITIUS'), ('MAYOTTE', 'MAYOTTE'), ('MEXICO', 'MEXICO'), ('MICRONESIA, FEDERATED STATES OF', 'MICRONESIA, FEDERATED STATES OF'), ('MOLDOVA, REPUBLIC OF', 'MOLDOVA, REPUBLIC OF'), ('MONACO', 'MONACO'), ('MONGOLIA', 'MONGOLIA'), ('MONTSERRAT', 'MONTSERRAT'), ('MOROCCO', 'MOROCCO'), ('MOZAMBIQUE', 'MOZAMBIQUE'), ('MYANMAR', 'MYANMAR'), ('NAMIBIA', 'NAMIBIA'), ('NAURU', 'NAURU'), ('NEPAL', 'NEPAL'), ('NETHERLANDS', 'NETHERLANDS'), ('NETHERLANDS ANTILLES', 'NETHERLANDS ANTILLES'), ('NEW CALEDONIA', 'NEW CALEDONIA'), ('NEW ZEALAND', 'NEW ZEALAND'), ('NICARAGUA', 'NICARAGUA'), ('NIGER', 'NIGER'), ('NIGERIA', 'NIGERIA'), ('NIUE', 'NIUE'), ('NORFOLK ISLAND', 'NORFOLK ISLAND'), ('NORTHERN MARIANA ISLANDS', 'NORTHERN MARIANA ISLANDS'), ('NORWAY', 'NORWAY'), ('OMAN', 'OMAN'), ('PAKISTAN', 'PAKISTAN'), ('PALAU', 'PALAU'), ('PALESTINIAN TERRITORY, OCCUPIED', 'PALESTINIAN TERRITORY, OCCUPIED'), ('PANAMA', 'PANAMA'), ('PAPUA NEW GUINEA', 'PAPUA NEW GUINEA'), ('PARAGUAY', 'PARAGUAY'), ('PERU', 'PERU'), ('PHILIPPINES', 'PHILIPPINES'), ('PITCAIRN', 'PITCAIRN'), ('POLAND', 'POLAND'), ('PORTUGAL', 'PORTUGAL'), ('PUERTO RICO', 'PUERTO RICO'), ('QATAR', 'QATAR'), ('REUNION', 'REUNION'), ('ROMANIA', 'ROMANIA'), ('RUSSIAN FEDERATION', 'RUSSIAN FEDERATION'), ('RWANDA', 'RWANDA'), ('SAINT HELENA', 'SAINT HELENA'), ('SAINT KITTS AND NEVIS', 'SAINT KITTS AND NEVIS'), ('SAINT LUCIA', 'SAINT LUCIA'), ('SAINT PIERRE AND MIQUELON', 'SAINT PIERRE AND MIQUELON'), ('SAINT VINCENT AND THE GRENADINES', 'SAINT VINCENT AND THE GRENADINES'), ('SAMOA', 'SAMOA'), ('SAN MARINO', 'SAN MARINO'), ('SAO TOME AND PRINCIPE', 'SAO TOME AND PRINCIPE'), ('SAUDI ARABIA', 'SAUDI ARABIA'), ('SENEGAL', 'SENEGAL'), ('SERBIA AND MONTENEGRO', 'SERBIA AND MONTENEGRO'), ('SEYCHELLES', 'SEYCHELLES'), ('SIERRA LEONE', 'SIERRA LEONE'), ('SINGAPORE', 'SINGAPORE'), ('SLOVAKIA', 'SLOVAKIA'), ('SLOVENIA', 'SLOVENIA'), ('SOLOMON ISLANDS', 'SOLOMON ISLANDS'), ('SOMALIA', 'SOMALIA'), ('SOUTH AFRICA', 'SOUTH AFRICA'), ('SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS', 'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS'), ('SPAIN', 'SPAIN'), ('SRI LANKA', 'SRI LANKA'), ('SUDAN', 'SUDAN'), ('SURINAME', 'SURINAME'), ('SVALBARD AND JAN MAYEN', 'SVALBARD AND JAN MAYEN'), ('SWAZILAND', 'SWAZILAND'), ('SWEDEN', 'SWEDEN'), ('SWITZERLAND', 'SWITZERLAND'), ('SYRIAN ARAB REPUBLIC', 'SYRIAN ARAB REPUBLIC'), ('TAIWAN, PROVINCE OF CHINA', 'TAIWAN, PROVINCE OF CHINA'), ('TAJIKISTAN', 'TAJIKISTAN'), ('TANZANIA, UNITED REPUBLIC OF', 'TANZANIA, UNITED REPUBLIC OF'), ('THAILAND', 'THAILAND'), ('TIMOR', 'TIMOR'), ('TOGO', 'TOGO'), ('TOKELAU', 'TOKELAU'), ('TONGA', 'TONGA'), ('TRINIDAD AND TOBAGO', 'TRINIDAD AND TOBAGO'), ('TUNISIA', 'TUNISIA'), ('TURKEY', 'TURKEY'), ('TURKMENISTAN', 'TURKMENISTAN'), ('TURKS AND CAICOS ISLANDS', 'TURKS AND CAICOS ISLANDS'), ('TUVALU', 'TUVALU'), ('UGANDA', 'UGANDA'), ('UKRAINE', 'UKRAINE'), ('UNITED ARAB EMIRATES', 'UNITED ARAB EMIRATES'), ('UNITED KINGDOM', 'UNITED KINGDOM'), ('UNITED STATES', 'UNITED STATES'), ('UNITED STATES MINOR OUTLYING ISLANDS', 'UNITED STATES MINOR OUTLYING ISLANDS'), ('URUGUAY', 'URUGUAY'), ('UZBEKISTAN', 'UZBEKISTAN'), ('VANUATU', 'VANUATU'), ('VIET NAM', 'VIET NAM'), ('VIRGIN ISLANDS, BRITISH', 'VIRGIN ISLANDS, BRITISH'), ('VIRGIN ISLANDS, U.S.', 'VIRGIN ISLANDS, U.S.'), ('WALLIS AND FUTUNA', 'WALLIS AND FUTUNA'), ('WESTERN SAHARA', 'WESTERN SAHARA'), ('YEMEN', 'YEMEN'), ('ZIMBABWE', 'ZIMBABWE')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('economic_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.economicdata')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start_date', models.DateTimeField()),
                ('time_step', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('capex_fix', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('capex_var', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('opex_fix', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('opex_var', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('evaluated_period', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='tempFiles/')),
            ],
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True)),
                ('unit', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('elapsed_seconds', models.FloatField(null=True)),
                ('mvs_token', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('ERROR', 'ERROR'), ('DONE', 'DONE'), ('PENDING', 'PENDING')], max_length=20)),
                ('user_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True)),
                ('results', models.TextField(max_length=30000000.0, null=True)),
                ('errors', models.TextField(null=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.scenario')),
            ],
        ),
    ]
