# Generated by Django 3.2 on 2021-07-09 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(related_name='viewer_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectionlink',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.asset'),
        ),
        migrations.AddField(
            model_name='connectionlink',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.bus'),
        ),
        migrations.AddField(
            model_name='connectionlink',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.scenario'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='bus',
            name='parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.asset'),
        ),
        migrations.AddField(
            model_name='bus',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.scenario'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='projects.assettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.asset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.scenario'),
        ),
    ]
