# Generated by Django 3.2 on 2021-09-29 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_dummyscenario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyScenario',
        ),
    ]
