# Generated by Django 3.2 on 2021-09-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_maxemissionconstraint_mindoaconstraint_minrenewableconstraint_nzeconstraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maxemissionconstraint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mindoaconstraint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='minrenewableconstraint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='nzeconstraint',
            name='name',
        ),
    ]
