# Generated by Django 3.2 on 2021-10-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20211006_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxemissionconstraint',
            name='unit',
            field=models.CharField(default='kgCO2eq/a', editable=False, max_length=9),
        ),
        migrations.AddField(
            model_name='mindoaconstraint',
            name='unit',
            field=models.CharField(default='factor', editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='minrenewableconstraint',
            name='unit',
            field=models.CharField(default='factor', editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='nzeconstraint',
            name='unit',
            field=models.CharField(default='bool', editable=False, max_length=4),
        ),
    ]
