# Generated by Django 3.2 on 2021-10-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20211012_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxemissionconstraint',
            name='name',
            field=models.CharField(default='maximum_emissions', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='mindoaconstraint',
            name='name',
            field=models.CharField(default='minimal_degree_of_autonomy', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='minrenewableconstraint',
            name='name',
            field=models.CharField(default='minimal_renewable_factor', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='nzeconstraint',
            name='name',
            field=models.CharField(default='net_zero_energy', editable=False, max_length=30),
        ),
    ]
