# Generated by Django 3.2 on 2021-10-13 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20211012_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minrenewableconstraint',
            name='value',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Minimal renewable_factor'),
        ),
    ]
