# Generated by Django 3.2 on 2021-10-13 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_minrenewableconstraint_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minrenewableconstraint',
            name='value',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
