# Generated by Django 3.2 on 2021-10-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_minrenewableconstraint_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='capex_fix',
            new_name='development_costs',
        ),
    ]
