# Generated by Django 3.2 on 2021-10-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_capex_fix_asset_development_costs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='development_costs',
            new_name='capex_fix',
        ),
    ]
