# Generated by Django 3.2 on 2021-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets_list', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KPICostsMatrixResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_values', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KPIScalarResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scalar_values', models.TextField()),
            ],
        ),
    ]
