# Generated by Django 3.2 on 2021-07-09 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiscalarresults',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.simulation'),
        ),
        migrations.AddField(
            model_name='kpicostsmatrixresults',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.simulation'),
        ),
        migrations.AddField(
            model_name='assetsresults',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.simulation'),
        ),
    ]
